server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: usermanagement
          uri: lb://usermanagement
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/usermanagement/(?<segment>.*), /${segment}
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
