server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: usermanagement
          uri: lb://usermanagement
          predicates:
            - Path=/api/users/**
  application:
    name: api-gateway