server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      routes:
        - id: usermanagement
          uri: lb://usermanagement
          predicates:
            - Path=/api/users/**
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
